# Generated by Django 2.2.6 on 2019-10-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyWalk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=25)),
                ("text", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "My walks dynamic text",
                "verbose_name_plural": "My walks dynamic text",
            },
        ),
        migrations.CreateModel(
            name="TodayWalk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_name", models.CharField(max_length=25)),
            ],
            options={
                "verbose_name": "Today's walks dynamic text",
                "verbose_name_plural": "Today's walks dynamic text",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=25)),
                ("text", models.CharField(max_length=255)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_walks.TodayWalk",
                    ),
                ),
            ],
        ),
    ]
