# Generated by Django 2.2.6 on 2019-10-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_walks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mywalk",
            name="condition",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="mywalk",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="target",
            name="condition",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="target",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="todaywalk",
            name="target_name",
            field=models.CharField(max_length=255),
        ),
    ]
