# Generated by Django 2.2.6 on 2019-12-13 13:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_walks", "0002_auto_20191016_0930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mywalk",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="target",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
