# Generated by Django 2.2.6 on 2020-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_walks", "0003_auto_20191213_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mywalk",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="target",
            name="text",
            field=models.TextField(),
        ),
    ]
