# Generated by Django 4.2.26 on 2026-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_walks", "0004_auto_20200413_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="mywalk",
            name="wheelchair_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="target",
            name="wheelchair_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
