# Generated by Django 2.2.6 on 2019-10-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SplashScreen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("text", models.TextField(max_length=255)),
                ("button", models.CharField(max_length=25)),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("message", models.CharField(max_length=255)),
                ("fulltext", models.TextField()),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Discover",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("description", models.TextField()),
                ("action", models.CharField(max_length=25)),
                ("colour", models.CharField(max_length=25)),
                ("border_colour", models.CharField(max_length=25)),
                (
                    "splash_screen",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discover.SplashScreen",
                    ),
                ),
            ],
        ),
    ]
