# Generated by Django 2.2.6 on 2019-10-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("button", models.CharField(max_length=25)),
                ("link", models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="discover",
            options={"verbose_name": "Discover", "verbose_name_plural": "Discover"},
        ),
        migrations.AlterModelOptions(
            name="tip",
            options={"verbose_name": "Tip", "verbose_name_plural": "Tips"},
        ),
        migrations.AddField(
            model_name="tip",
            name="cta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="discover.Cta",
            ),
        ),
    ]
