# Generated by Django 2.2.6 on 2019-10-16 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0002_auto_20191015_1437"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cta",
            options={"verbose_name": "cta", "verbose_name_plural": "cta"},
        ),
    ]
