# Generated by Django 2.2.6 on 2019-10-17 10:25

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0003_auto_20191016_0920"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discover",
            name="border_colour",
            field=colorful.fields.RGBColorField(default="#32B678"),
        ),
        migrations.AlterField(
            model_name="discover",
            name="colour",
            field=colorful.fields.RGBColorField(default="#32B678"),
        ),
    ]
