# Generated by Django 2.2.6 on 2019-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0004_auto_20191017_1025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cta",
            name="button",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="discover",
            name="action",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="discover",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="button",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tip",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
