# Generated by Django 2.2.6 on 2019-11-22 16:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0005_auto_20191023_1438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cta",
            name="button",
            field=models.CharField(max_length=25, verbose_name="Button (25 chars max)"),
        ),
        migrations.AlterField(
            model_name="discover",
            name="action",
            field=models.CharField(max_length=15, verbose_name="Action (15 chars max)"),
        ),
        migrations.AlterField(
            model_name="discover",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(70)],
                verbose_name="Description (70 chars max)",
            ),
        ),
        migrations.AlterField(
            model_name="discover",
            name="name",
            field=models.CharField(max_length=15, verbose_name="Name (15 chars max)"),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="button",
            field=models.CharField(max_length=25, verbose_name="Button (25 chars max)"),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="text",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(400)],
                verbose_name="Text (400 chars max)",
            ),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="title",
            field=models.CharField(max_length=20, verbose_name="Title (20 chars max)"),
        ),
        migrations.AlterField(
            model_name="tip",
            name="cta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="discover.Cta",
            ),
        ),
        migrations.AlterField(
            model_name="tip",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Title (50 chars max)"),
        ),
    ]
