# Generated by Django 2.2.6 on 2019-12-13 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0006_auto_20191122_1632"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discover",
            name="action",
            field=models.CharField(max_length=20, verbose_name="Action (15 chars max)"),
        ),
        migrations.AlterField(
            model_name="discover",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="Description (200 chars max)",
            ),
        ),
        migrations.AlterField(
            model_name="discover",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Name (15 chars max)"),
        ),
    ]
