# Generated by Django 2.2.6 on 2019-12-13 13:24

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0007_auto_20191213_0927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discover",
            name="action",
            field=models.CharField(max_length=20, verbose_name="Action (20 chars max)"),
        ),
        migrations.AlterField(
            model_name="discover",
            name="description",
            field=ckeditor.fields.RichTextField(
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="Description (200 chars max)",
            ),
        ),
        migrations.AlterField(
            model_name="discover",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Name (20 chars max)"),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="text",
            field=ckeditor.fields.RichTextField(
                validators=[django.core.validators.MaxLengthValidator(400)],
                verbose_name="Text (400 chars max)",
            ),
        ),
        migrations.AlterField(
            model_name="tip",
            name="fulltext",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
