# Generated by Django 2.2.6 on 2019-12-19 15:33

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0008_auto_20191213_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cta",
            name="button",
            field=models.CharField(help_text="Max: 25 symbols", max_length=25),
        ),
        migrations.AlterField(
            model_name="discover",
            name="action",
            field=models.CharField(help_text="Max: 20 symbols", max_length=20),
        ),
        migrations.AlterField(
            model_name="discover",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Max: 250 symbols",
                validators=[django.core.validators.MaxLengthValidator(250)],
            ),
        ),
        migrations.AlterField(
            model_name="discover",
            name="name",
            field=models.CharField(help_text="Max: 20 symbols", max_length=20),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="button",
            field=models.CharField(help_text="Max: 25 symbols", max_length=25),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="text",
            field=ckeditor.fields.RichTextField(
                help_text="Text (450 chars max)",
                validators=[django.core.validators.MaxLengthValidator(450)],
            ),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="title",
            field=models.CharField(help_text="Max: 20 symbols", max_length=20),
        ),
        migrations.AlterField(
            model_name="tip",
            name="title",
            field=models.CharField(help_text="Max: 50 symbols", max_length=50),
        ),
    ]
