# Generated by Django 2.2.6 on 2020-04-13 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0009_auto_20191219_1533"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discover",
            options={
                "ordering": ["list_order"],
                "verbose_name": "Discover",
                "verbose_name_plural": "Discover",
            },
        ),
        migrations.AlterModelOptions(
            name="splashscreen",
            options={"ordering": ["list_order"]},
        ),
        migrations.AddField(
            model_name="discover",
            name="list_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Ascending ordering, 0 be first"
            ),
        ),
        migrations.AddField(
            model_name="splashscreen",
            name="list_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Ascending ordering, 0 be first"
            ),
        ),
        migrations.AlterField(
            model_name="discover",
            name="description",
            field=models.TextField(
                help_text="Max: 250 symbols",
                validators=[django.core.validators.MaxLengthValidator(250)],
            ),
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="text",
            field=models.TextField(
                help_text="Text (450 chars max)",
                validators=[django.core.validators.MaxLengthValidator(450)],
            ),
        ),
        migrations.AlterField(
            model_name="tip",
            name="fulltext",
            field=models.TextField(),
        ),
    ]
