# Generated by Django 2.2.6 on 2020-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0010_auto_20200413_1339"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discover",
            name="name",
        ),
        migrations.AddField(
            model_name="discover",
            name="name_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="discover",
            name="name_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discover",
            name="name_text",
            field=models.CharField(
                blank=True, help_text="Max: 20 symbols", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="discover",
            name="name_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("image_url", "Image url"),
                    ("text", "Text"),
                ],
                default="text",
                max_length=25,
            ),
        ),
    ]
