# Generated by Django 2.2.6 on 2020-04-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0011_auto_20200413_1557"),
    ]

    operations = [
        migrations.AddField(
            model_name="discover",
            name="alt_text",
            field=models.CharField(
                blank=True, help_text="alt text for image", max_length=255, null=True
            ),
        ),
    ]
