# Generated by Django 2.2.6 on 2020-04-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0012_discover_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="list_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Ascending ordering, 0 be first"
            ),
        ),
    ]
