# Generated by Django 2.2.6 on 2020-04-17 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0013_tip_list_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="splashscreen",
            options={},
        ),
        migrations.RemoveField(
            model_name="splashscreen",
            name="list_order",
        ),
    ]
