# Generated by Django 2.2.6 on 2020-06-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0014_auto_20200417_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="splashscreen",
            name="android_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="splashscreen",
            name="ios_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="splashscreen",
            name="is_app",
            field=models.BooleanField(default=False),
        ),
    ]
