# Generated by Django 2.2.6 on 2020-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0015_auto_20200618_0555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="splashscreen",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
