# Generated by Django 2.2.6 on 2020-07-07 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0016_auto_20200623_0935"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cta",
            options={"verbose_name": "CTA", "verbose_name_plural": "CTA"},
        ),
        migrations.AlterModelOptions(
            name="splashscreen",
            options={
                "verbose_name": "Splash Screen",
                "verbose_name_plural": "Splash Screen",
            },
        ),
    ]
