# Generated by Django 2.2.6 on 2021-06-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0017_auto_20200707_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="discover",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
