# Generated by Django 3.1.2 on 2021-10-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0018_discover_header_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tip",
            options={"verbose_name": "Carousel", "verbose_name_plural": "Carousels"},
        ),
        migrations.AlterField(
            model_name="splashscreen",
            name="text",
            field=models.TextField(),
        ),
    ]
