# Generated by Django 3.1.2 on 2021-10-11 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0019_auto_20211008_1333"),
    ]

    operations = [migrations.RenameModel("Tip", "Carousel")]
