# Generated by Django 3.1.2 on 2021-10-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discover", "0020_auto_20211011_0821"),
    ]

    operations = [
        migrations.AddField(
            model_name="discover",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
