# Generated by Django 3.1.2 on 2022-03-25 14:21

from django.db import migrations, models
import django.db.models.deletion
import utils.image
import utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="View",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("root_page", "root_page"),
                            ("carousel_small_items", "carousel_small_items"),
                            ("carousel_double_items", "carousel_double_items"),
                            ("carousel_large_items", "carousel_large_items"),
                            ("carousel_goals", "carousel_goals"),
                            ("hero_item", "hero_item"),
                            ("article_list", "article_list"),
                            ("article_list_small_items", "article_list_small_items"),
                            ("popup", "popup"),
                        ],
                        default="root_page",
                        max_length=100,
                    ),
                ),
                ("slug", models.CharField(max_length=256)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, default="", null=True)),
                (
                    "analytics_tag",
                    models.CharField(blank=True, default="", max_length=128, null=True),
                ),
                (
                    "articles",
                    models.ManyToManyField(
                        through="articles.ArticleView", to="articles.Article"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ViewsRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("alternative_order", models.PositiveIntegerField(default=0)),
                (
                    "child",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="views.view",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="views.view",
                    ),
                ),
            ],
            options={
                "ordering": ("-order",),
                "unique_together": {("parent", "child")},
            },
        ),
        migrations.CreateModel(
            name="ViewProperty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=256)),
                ("value", models.TextField()),
                (
                    "view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_property",
                        to="views.view",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViewMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=256)),
                ("tag", models.CharField(max_length=256)),
                (
                    "url",
                    models.FileField(
                        blank=True,
                        upload_to=utils.image.path_and_rename_image,
                        validators=[utils.validators.validate_image_extension],
                    ),
                ),
                ("resource_id", models.CharField(max_length=256)),
                ("label", models.CharField(max_length=256)),
                (
                    "view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_media",
                        to="views.view",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="view",
            name="views",
            field=models.ManyToManyField(
                through="views.ViewsRelation", to="views.View"
            ),
        ),
    ]
