# Generated by Django 4.2.18 on 2025-03-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("views", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="version",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="viewproperty",
            name="value",
            field=models.TextField(blank=True),
        ),
    ]
