# Generated by Django 2.2.6 on 2020-06-11 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="global_rules.App",
                    ),
                ),
                ("latest_version", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
                ("button", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TermsConditions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latest_version", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
                ("button", models.CharField(max_length=200)),
                ("agree", models.CharField(max_length=200)),
                ("links", models.ManyToManyField(blank=True, to="global_rules.Link")),
            ],
        ),
    ]
