# Generated by Django 2.2.6 on 2020-06-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_rules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissingData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text_android", models.TextField()),
                ("text_ios", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="app",
            options={
                "verbose_name": "Operating System",
                "verbose_name_plural": "Operating Systems",
            },
        ),
        migrations.AlterModelOptions(
            name="appversion",
            options={
                "verbose_name": "Mobile App Version",
                "verbose_name_plural": "Mobile App Versions",
            },
        ),
    ]
