# Generated by Django 2.2.6 on 2020-06-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_rules", "0002_auto_20200612_0738"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missingdata",
            name="title",
        ),
        migrations.AddField(
            model_name="missingdata",
            name="title_android",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="missingdata",
            name="title_ios",
            field=models.CharField(default="", max_length=200),
        ),
    ]
