# Generated by Django 2.2.6 on 2020-07-07 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("global_rules", "0003_auto_20200623_0726"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missingdata",
            options={
                "verbose_name": "Missing Data",
                "verbose_name_plural": "Missing Data",
            },
        ),
        migrations.AlterModelOptions(
            name="termsconditions",
            options={
                "verbose_name": "Terms & Conditions",
                "verbose_name_plural": "Terms & Conditions",
            },
        ),
    ]
