# Generated by Django 2.2.6 on 2020-09-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_rules", "0004_auto_20200707_1336"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessibility",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")], max_length=200
                    ),
                ),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name": "Accessibility Statement",
                "verbose_name_plural": "Accessibility Statement",
            },
        ),
    ]
