# Generated by Django 2.2.6 on 2020-09-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_rules", "0005_accessibility"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accessibility",
            constraint=models.UniqueConstraint(
                fields=("device",), name="unique device"
            ),
        ),
    ]
