# Generated by Django 2.2.6 on 2021-05-05 10:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("global_rules", "0006_auto_20200901_0229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibility",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
