# Generated by Django 2.2.6 on 2019-11-22 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tips", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintip",
            options={"verbose_name": "Tip", "verbose_name_plural": "Tips"},
        ),
        migrations.AddField(
            model_name="maintip",
            name="list_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="maintip",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="Description (200 chars max)",
            ),
        ),
        migrations.AlterField(
            model_name="maintip",
            name="title",
            field=models.CharField(max_length=20, verbose_name="Title (20 chars max)"),
        ),
    ]
