# Generated by Django 2.2.6 on 2019-12-19 15:33

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tips", "0003_auto_20191213_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintip",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="Max: 250 symbols",
                validators=[django.core.validators.MaxLengthValidator(250)],
            ),
        ),
        migrations.AlterField(
            model_name="maintip",
            name="title",
            field=models.CharField(help_text="Max: 20 symbols", max_length=20),
        ),
    ]
