# Generated by Django 2.2.6 on 2020-04-13 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tips", "0004_auto_20191219_1533"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintip",
            name="description",
            field=models.TextField(
                help_text="Max: 250 symbols",
                validators=[django.core.validators.MaxLengthValidator(250)],
            ),
        ),
    ]
