# Generated by Django 3.1.2 on 2021-10-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tips", "0005_auto_20200413_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintip",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
