# Generated by Django 4.2.26 on 2026-07-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tips", "0007_maintip_activity_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintip",
            options={"ordering": ["list_order", "id"], "verbose_name": "Tip", "verbose_name_plural": "Tips"},
        ),
    ]
