# Generated by Django 2.2.6 on 2019-10-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("user", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "User goal",
                "verbose_name_plural": "User goals",
            },
        ),
    ]
