# Generated by Django 2.2.6 on 2019-12-13 13:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
