# Generated by Django 2.2.6 on 2020-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0002_auto_20191213_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="text",
            field=models.TextField(),
        ),
    ]
