# Generated by Django 4.2.18 on 2025-04-24 15:03

from django.db import migrations, models

from applications.goals.models import Goal


def add_starting_order(apps, schema_editor):
    order_idx = 0
    for obj in Goal.objects.all():
        order_idx += 1
        obj.order = order_idx
        obj.save()

    orderfield = Goal._meta.ordering[0]
    if orderfield[0] == "-":
        orderfield = orderfield[1:]

    for order_idx, obj in enumerate(Goal.objects.iterator(), start=1):
        setattr(obj, orderfield, order_idx)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0003_auto_20200413_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterModelOptions(
            name="goal",
            options={
                "ordering": ["order"],
                "verbose_name": "User goal",
                "verbose_name_plural": "User goals",
            },
        ),
        migrations.RunPython(
            add_starting_order, reverse_code=migrations.RunPython.noop
        ),
    ]
