# Generated by Django 4.2.18 on 2025-04-24 15:03

from django.db import migrations, models


def add_starting_order(apps, schema_editor):
    # Use the historical model (not the concrete import) so this data migration
    # keeps working as the Goal model gains fields in later migrations.
    Goal = apps.get_model("goals", "Goal")
    for order_idx, obj in enumerate(Goal.objects.all(), start=1):
        obj.order = order_idx
        obj.save(update_fields=["order"])


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_auto_20200413_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterModelOptions(
            name="goal",
            options={"ordering": ["order"], "verbose_name": "User goal", "verbose_name_plural": "User goals"},
        ),
        migrations.RunPython(add_starting_order, reverse_code=migrations.RunPython.noop),
    ]
