# Generated by Django 4.2.18 on 2026-06-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0004_alter_goal_options_goal_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="activity_type",
            field=models.CharField(choices=[("walking", "Walking journey"), ("wheeling", "Wheeling journey"), ("both", "Walking and Wheeling")], default="walking", help_text="Which app journey shows this content. 'Both' shows on walking and wheeling.", max_length=16, verbose_name="Activity type"),
        ),
    ]
