# Generated by Django 2.2.6 on 2019-10-15 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ", "verbose_name_plural": "FAQs"},
        ),
    ]
