# Generated by Django 2.2.6 on 2019-11-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0002_auto_20191015_1437"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="list_order",
            field=models.IntegerField(default=0),
        ),
    ]
