# Generated by Django 2.2.6 on 2019-11-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0003_faq_list_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="list_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
