# Generated by Django 2.2.6 on 2019-12-13 13:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0004_auto_20191122_1648"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
