# Generated by Django 2.2.6 on 2019-11-22 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("how_it_works", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="howitworks",
            name="list_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="howitworks",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(100)],
                verbose_name="Description (100 chars max)",
            ),
        ),
        migrations.AlterField(
            model_name="howitworks",
            name="title",
            field=models.CharField(max_length=20, verbose_name="Title (20 chars max)"),
        ),
    ]
