# Generated by Django 2.2.6 on 2019-12-13 13:24

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("how_it_works", "0002_auto_20191122_1632"),
    ]

    operations = [
        migrations.AlterField(
            model_name="howitworks",
            name="description",
            field=ckeditor.fields.RichTextField(
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Description (150 chars max)",
            ),
        ),
    ]
