# Generated by Django 2.2.6 on 2020-04-13 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("how_it_works", "0004_auto_20191219_1533"),
    ]

    operations = [
        migrations.AlterField(
            model_name="howitworks",
            name="description",
            field=models.TextField(
                help_text="Max: 200 symbols",
                validators=[django.core.validators.MaxLengthValidator(200)],
            ),
        ),
    ]
