# Generated by Django 4.2.26 on 2026-07-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('how_it_works', '0006_howitworks_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howitworks',
            options={'ordering': ['list_order', 'id'], 'verbose_name': 'How It Works', 'verbose_name_plural': 'How It Works'},
        ),
    ]
