# Generated by Django 3.1.2 on 2022-03-25 14:21

import applications.articles.utils.image
import applications.articles.utils.subject_optimized_image_field
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                (
                    "slug",
                    models.CharField(
                        blank=True, help_text="Max 128 characters", max_length=128
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Max 128 characters", max_length=128),
                ),
                (
                    "description",
                    models.CharField(help_text="Max 512 characters", max_length=512),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("content", "Content"),
                            ("container", "Container"),
                            ("link", "Link"),
                        ],
                        default="content",
                        max_length=16,
                    ),
                ),
                (
                    "destination_ios",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Max 128 characters, LINK: url for external website, CONTAINER: view's slug",
                        max_length=128,
                    ),
                ),
                (
                    "destination_android",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Max 128 characters, LINK: url for external website, CONTAINER: view's slug",
                        max_length=128,
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(blank=True, default="")),
                (
                    "analytics_tag",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Max 64 characters",
                        max_length=64,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("ios", "Ios"),
                            ("android", "Android"),
                        ],
                        default="all",
                        max_length=7,
                    ),
                ),
                (
                    "button_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Max 32 characters",
                        max_length=32,
                    ),
                ),
                (
                    "button_analytics_tag",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Max 64 characters",
                        max_length=64,
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Max 128 characters",
                        max_length=128,
                    ),
                ),
                (
                    "button_accessibility_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Max 64 characters",
                        max_length=64,
                    ),
                ),
                (
                    "related_section_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Max 128 characters",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "related_section_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Max 256 characters",
                        max_length=256,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=256)),
                ("position", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Article Categories",
            },
        ),
        migrations.CreateModel(
            name="ArticleRelated",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Related articles",
                "verbose_name_plural": "Related articles",
                "ordering": ("-order",),
            },
        ),
        migrations.CreateModel(
            name="ArticleView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("-order",),
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "image",
                    applications.articles.utils.subject_optimized_image_field.SubjectOptimizedImageField(
                        help_text="Max 50MB",
                        subject_location_field="subject_location",
                        upload_to=applications.articles.utils.image.path_and_rename_image,
                    ),
                ),
                (
                    "subject_location",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="subject coords"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "content view",
                "verbose_name_plural": "content views",
                "ordering": ["order"],
            },
        ),
    ]
