# Generated by Django 3.1.2 on 2022-03-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("views", "0001_initial"),
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentview",
            name="view",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="views.view"
            ),
        ),
        migrations.AddField(
            model_name="articleview",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="articleview",
            name="view",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="views.view"
            ),
        ),
        migrations.AddField(
            model_name="articlerelated",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_article",
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="articlerelated",
            name="related_article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_article",
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.articlecategory",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.image",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="related",
            field=models.ManyToManyField(
                through="articles.ArticleRelated", to="articles.Article"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.ManyToManyField(
                through="articles.ArticleView", to="views.View"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articleview",
            unique_together={("article", "view")},
        ),
        migrations.AlterUniqueTogether(
            name="articlerelated",
            unique_together={("article", "related_article")},
        ),
    ]
