# Generated by Django 4.2.18 on 2025-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_auto_20220325_1421"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="user_group",
            field=models.CharField(
                choices=[
                    ("all_users", "All users"),
                    ("nhs_users", "NHS users"),
                    ("users", "User without NHS account"),
                ],
                default="all_users",
                max_length=64,
                verbose_name="Filter for content to be published for the following user groups",
            ),
        ),
    ]
