# Generated by Django 2.2.6 on 2019-10-15 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about_one_you", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutoneyou",
            options={
                "verbose_name": "About One You",
                "verbose_name_plural": "About One You",
            },
        ),
        migrations.AlterModelOptions(
            name="application",
            options={"verbose_name": "App", "verbose_name_plural": "Apps"},
        ),
    ]
