# Generated by Django 2.2.6 on 2019-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about_one_you", "0002_auto_20191015_1437"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
