# Generated by Django 2.2.6 on 2019-11-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about_one_you", "0003_auto_20191023_1438"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="list_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
