# Generated by Django 2.2.6 on 2019-12-13 13:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about_one_you", "0004_application_list_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
