# Generated by Django 2.2.6 on 2019-12-19 15:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about_one_you", "0005_auto_20191213_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutoneyou",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
