# Generated by Django 2.2.6 on 2020-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about_one_you", "0006_auto_20191219_1533"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "ordering": ["list_order"],
                "verbose_name": "App",
                "verbose_name_plural": "Apps",
            },
        ),
        migrations.AlterField(
            model_name="aboutoneyou",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="application",
            name="description",
            field=models.TextField(),
        ),
    ]
