# Generated by Django 2.2.6 on 2020-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about_one_you", "0007_auto_20200413_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="list_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Ascending ordering, 0 be first"
            ),
        ),
    ]
