# Generated by Django 3.1.2 on 2021-10-11 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about_one_you", "0008_auto_20200413_1557"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutoneyou",
            options={
                "verbose_name": "About Better Health",
                "verbose_name_plural": "About Better Health",
            },
        ),
    ]
