# Generated by Django 3.1.2 on 2024-04-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlanCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("18 to 24", "Eighteen To Twentyfour"),
                            ("25 to 34", "Twentyfive To Thirtyfour"),
                            ("35 to 44", "Thirtyfive To Fourtyfour"),
                            ("45 to 54", "Fourtyfive To Fiftyfour"),
                            ("55 to 64", "Fiftyfive To Sixtyfour"),
                            ("65 or over", "Sixtyfive Or Over"),
                        ],
                        default="18 to 24",
                        max_length=32,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=32,
                    ),
                ),
                (
                    "motivation",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Inactive", "Inactive"),
                            ("Moderately active", "Moderately Active"),
                            ("Active", "Active"),
                        ],
                        default="",
                        max_length=128,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalkingPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="walking_plans/"
                    ),
                ),
                ("plan_name", models.CharField(blank=True, default="", max_length=256)),
                (
                    "plan_tagline",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("plan_description", models.TextField(blank=True, default="")),
                (
                    "plan_duration",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "plan_brisk_minutes_per_day",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("plan_goal", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="PlanItineraryItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_label",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "description_of_weekly_task",
                    models.TextField(blank=True, default=""),
                ),
                ("total_brisk_minutes", models.PositiveIntegerField(default=0)),
                (
                    "walking_plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="walking_plans.walkingplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanCategoryWalkingPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "plan_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="walking_plans.plancategory",
                    ),
                ),
                (
                    "walking_plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="walking_plans.walkingplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="plancategory",
            name="walking_plans",
            field=models.ManyToManyField(
                through="walking_plans.PlanCategoryWalkingPlan",
                to="walking_plans.WalkingPlan",
            ),
        ),
    ]
