# Generated by Django 3.1.2 on 2024-04-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plancategory",
            options={"verbose_name_plural": "Plan categories"},
        ),
        migrations.AlterField(
            model_name="walkingplan",
            name="plan_brisk_minutes_per_day",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
