# Generated by Django 3.1.2 on 2024-04-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0002_auto_20240430_0841"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planitineraryitem",
            name="walking_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_itinerary_items",
                to="walking_plans.walkingplan",
            ),
        ),
    ]
