# Generated by Django 3.1.2 on 2024-04-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0003_auto_20240430_0946"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkingplan",
            name="categories",
            field=models.ManyToManyField(
                through="walking_plans.PlanCategoryWalkingPlan",
                to="walking_plans.PlanCategory",
            ),
        ),
        migrations.AlterField(
            model_name="plancategory",
            name="age",
            field=models.CharField(
                choices=[
                    ("18 to 24", "18 to 24"),
                    ("25 to 34", "25 to 34"),
                    ("35 to 44", "35 to 44"),
                    ("45 to 54", "45 to 54"),
                    ("55 to 64", "55 to 64"),
                    ("65 or over", "65 or over"),
                ],
                default="18 to 24",
                max_length=32,
            ),
        ),
    ]
