# Generated by Django 3.1.2 on 2024-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0004_auto_20240430_0957"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkingplan",
            name="plan_duration_short",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
