# Generated by Django 3.1.2 on 2024-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0005_walkingplan_plan_duration_short"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plancategory",
            name="age",
            field=models.CharField(
                blank=True,
                choices=[
                    ("18 to 24", "18 to 24"),
                    ("25 to 34", "25 to 34"),
                    ("35 to 44", "35 to 44"),
                    ("45 to 54", "45 to 54"),
                    ("55 to 64", "55 to 64"),
                    ("65 or over", "65 or over"),
                ],
                default="18 to 24",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plancategory",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=32,
                null=True,
            ),
        ),
    ]
