# Generated by Django 3.1.2 on 2024-05-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0003_auto_20200413_1339"),
        ("walking_plans", "0006_auto_20240509_0628"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plancategory",
            name="motivation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goals.goal",
            ),
        ),
    ]
