# Generated by Django 3.1.2 on 2024-05-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0007_auto_20240509_0633"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walkingplan",
            name="plan_duration_short",
        ),
        migrations.AddField(
            model_name="walkingplan",
            name="plan_duration_weeks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
