# Generated by Django 3.1.2 on 2024-05-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0002_auto_20201204_0530"),
        ("walking_plans", "0008_auto_20240509_0739"),
    ]

    operations = [
        migrations.AddField(
            model_name="planitineraryitem",
            name="reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rewards.reward",
            ),
        ),
    ]
