# Generated by Django 3.1.2 on 2024-05-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0003_auto_20200413_1339"),
        ("walking_plans", "0010_auto_20240514_1123"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Age",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Sex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name="plancategory",
            name="label",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.RemoveField(
            model_name="plancategory",
            name="activity_level",
        ),
        migrations.RemoveField(
            model_name="plancategory",
            name="age",
        ),
        migrations.RemoveField(
            model_name="plancategory",
            name="motivation",
        ),
        migrations.AddField(
            model_name="plancategory",
            name="motivation",
            field=models.ManyToManyField(blank=True, to="goals.Goal"),
        ),
        migrations.RemoveField(
            model_name="plancategory",
            name="sex",
        ),
        migrations.AddField(
            model_name="plancategory",
            name="activity_level",
            field=models.ManyToManyField(blank=True, to="walking_plans.ActivityLevel"),
        ),
        migrations.AddField(
            model_name="plancategory",
            name="age",
            field=models.ManyToManyField(blank=True, to="walking_plans.Age"),
        ),
        migrations.AddField(
            model_name="plancategory",
            name="sex",
            field=models.ManyToManyField(blank=True, to="walking_plans.Sex"),
        ),
    ]
