# Generated by Django 3.1.2 on 2024-05-22 12:22

from django.db import migrations


def populate_sex(apps, schema):
    Sex = apps.get_model("walking_plans", "Sex")

    Sex.objects.create(label="Male")
    Sex.objects.create(label="Female")


def populate_activity_level(apps, schema):
    ActivityLevel = apps.get_model("walking_plans", "ActivityLevel")

    ActivityLevel.objects.create(label="Inactive")
    ActivityLevel.objects.create(label="Moderately active")
    ActivityLevel.objects.create(label="Active")


def populate_age(apps, schema):
    Age = apps.get_model("walking_plans", "Age")

    Age.objects.create(label="18 to 24")
    Age.objects.create(label="25 to 34")
    Age.objects.create(label="35 to 44")
    Age.objects.create(label="45 to 54")
    Age.objects.create(label="55 to 64")
    Age.objects.create(label="65 or over")


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0011_auto_20240522_1218"),
    ]

    operations = [
        migrations.RunPython(populate_sex),
        migrations.RunPython(populate_activity_level),
        migrations.RunPython(populate_age),
    ]
