# Generated by Django 3.1.2 on 2024-05-22 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0012_populate_categorical_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plancategory",
            name="walking_plans",
        ),
        migrations.RemoveField(
            model_name="walkingplan",
            name="categories",
        ),
        migrations.DeleteModel(
            name="PlanCategoryWalkingPlan",
        ),
    ]
