# Generated by Django 3.1.2 on 2024-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0013_auto_20240522_1244"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkingplan",
            name="categories",
            field=models.ManyToManyField(to="walking_plans.PlanCategory"),
        ),
    ]
