# Generated by Django 3.1.2 on 2024-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0003_auto_20200413_1339"),
        ("walking_plans", "0014_walkingplan_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walkingplan",
            name="categories",
        ),
        migrations.AddField(
            model_name="walkingplan",
            name="activity_level",
            field=models.ManyToManyField(blank=True, to="walking_plans.ActivityLevel"),
        ),
        migrations.AddField(
            model_name="walkingplan",
            name="age",
            field=models.ManyToManyField(blank=True, to="walking_plans.Age"),
        ),
        migrations.AddField(
            model_name="walkingplan",
            name="motivation",
            field=models.ManyToManyField(blank=True, to="goals.Goal"),
        ),
        migrations.AddField(
            model_name="walkingplan",
            name="sex",
            field=models.ManyToManyField(blank=True, to="walking_plans.Sex"),
        ),
    ]
