# Generated by Django 3.1.2 on 2024-07-24 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0015_auto_20240724_0926"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlanCategory",
        ),
    ]
