# Generated by Django 3.1.2 on 2024-07-25 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0016_delete_plancategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkingplan",
            name="inferior_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="superior_plans",
                to="walking_plans.walkingplan",
            ),
        ),
        migrations.AddField(
            model_name="walkingplan",
            name="superior_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="inferior_plans",
                to="walking_plans.walkingplan",
            ),
        ),
    ]
