# Generated by Django 4.2.13 on 2024-07-26 08:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0017_auto_20240725_2219"),
    ]

    operations = [
        migrations.AddField(
            model_name="planitineraryitem",
            name="daily_brisk_minutes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(), default=list, size=7
            ),
        ),
    ]
