# Generated by Django 4.2.14 on 2024-07-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0018_planitineraryitem_daily_brisk_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkingplan",
            name="plan_difficulty",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
