# Generated by Django 4.2.14 on 2024-07-26 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0019_walkingplan_plan_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="planitineraryitem",
            name="daily_non_brisk_minutes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(), default=list, size=7
            ),
        ),
        migrations.AddField(
            model_name="planitineraryitem",
            name="total_non_brisk_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
