# Generated by Django 4.2.15 on 2024-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0020_planitineraryitem_daily_non_brisk_minutes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planitineraryitem",
            options={"ordering": ["ordering"]},
        ),
        migrations.AddField(
            model_name="planitineraryitem",
            name="ordering",
            field=models.PositiveIntegerField(default=0, verbose_name="ordering"),
        ),
    ]
