# Generated by Django 4.2.15 on 2024-08-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0021_alter_planitineraryitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walkingplan",
            name="plan_brisk_minutes_per_day",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
