# Generated by Django 4.2.15 on 2024-08-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0022_alter_walkingplan_plan_brisk_minutes_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkingplan",
            name="plan_full_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
