# Generated by Django 4.2.16 on 2025-01-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walking_plans", "0023_walkingplan_plan_full_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkingplan",
            name="plan_code",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
