# Generated by Django 2.2.6 on 2020-05-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "User Info",
                "verbose_name_plural": "User Info's",
            },
        ),
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(default=0)),
                ("copy", models.TextField()),
                (
                    "userinfo",
                    models.ManyToManyField(blank=True, to="notifications.UserInfo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lapsed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ident", models.CharField(max_length=200)),
                ("copy", models.TextField()),
                (
                    "userinfo",
                    models.ManyToManyField(blank=True, to="notifications.UserInfo"),
                ),
            ],
        ),
    ]
