# Generated by Django 2.2.6 on 2020-07-07 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_reminder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lapsed",
            options={"verbose_name": "Lapsed", "verbose_name_plural": "Lapsed"},
        ),
        migrations.AlterModelOptions(
            name="onboarding",
            options={"verbose_name": "Onboarding", "verbose_name_plural": "Onboarding"},
        ),
    ]
