# Generated by Django 4.2.14 on 2024-08-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_auto_20200707_1336"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField()),
                (
                    "destination",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("isLapsed", models.BooleanField(default=False)),
            ],
        ),
    ]
