# Generated by Django 4.2.18 on 2025-09-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_localnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="lapsed",
            name="days",
            field=models.IntegerField(default=5),
        ),
    ]
