# Generated by Django 4.2.26 on 2026-07-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_lapsed_activity_type_onboarding_activity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localnotification",
            name="activity_type",
            field=models.CharField(choices=[("walking", "Walking journey"), ("wheeling", "Wheeling journey"), ("both", "Walking and Wheeling")], default="walking", help_text="Which app journey shows this content. 'Both' shows on walking and wheeling.", max_length=16, verbose_name="Activity type"),
        ),
    ]
