# Generated by Django 2.2.6 on 2019-10-31 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReadyToGetStarted",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_new_user", models.TextField()),
                ("intro_migrating_user", models.TextField()),
                ("motion_fitness", models.TextField()),
                ("location", models.TextField()),
                ("notifications", models.TextField()),
                ("terms_link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motion_fitness", models.TextField()),
                ("location", models.TextField()),
                ("notifications", models.TextField()),
                ("goals", models.TextField()),
                (
                    "ready_to_get_started",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="onboarding.ReadyToGetStarted",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding",
                "verbose_name_plural": "Onboarding",
            },
        ),
    ]
