# Generated by Django 2.2.6 on 2019-11-15 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onboarding",
            options={
                "verbose_name": "On boarding",
                "verbose_name_plural": "On boarding",
            },
        ),
        migrations.AlterModelOptions(
            name="readytogetstarted",
            options={
                "verbose_name": "Ready to get started",
                "verbose_name_plural": "Ready to get started",
            },
        ),
    ]
