# Generated by Django 2.2.6 on 2019-11-15 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0002_auto_20191115_1419"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onboarding",
            name="ready_to_get_started",
        ),
    ]
