# Generated by Django 2.2.6 on 2019-12-13 13:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0003_remove_onboarding_ready_to_get_started"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboarding",
            name="goals",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="location",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="motion_fitness",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="notifications",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="intro_migrating_user",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="intro_new_user",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="location",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="motion_fitness",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="notifications",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="terms_link",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
