# Generated by Django 2.2.6 on 2020-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0004_auto_20191213_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboarding",
            name="goals",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="location",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="motion_fitness",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="notifications",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="intro_migrating_user",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="intro_new_user",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="location",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="motion_fitness",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="notifications",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="readytogetstarted",
            name="terms_link",
            field=models.TextField(),
        ),
    ]
