# Generated by Django 2.2.6 on 2021-07-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0005_auto_20200413_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboarding",
            name="about_you",
            field=models.TextField(blank=True, null=True),
        ),
    ]
