# Generated by Django 4.2.18 on 2026-06-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0006_onboarding_about_you"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboarding",
            name="activity_type",
            field=models.CharField(choices=[("walking", "Walking journey"), ("wheeling", "Wheeling journey"), ("both", "Walking and Wheeling")], default="walking", help_text="Which app journey shows this content. 'Both' shows on walking and wheeling.", max_length=16, verbose_name="Activity type"),
        ),
        migrations.AddField(
            model_name="readytogetstarted",
            name="activity_type",
            field=models.CharField(choices=[("walking", "Walking journey"), ("wheeling", "Wheeling journey"), ("both", "Walking and Wheeling")], default="walking", help_text="Which app journey shows this content. 'Both' shows on walking and wheeling.", max_length=16, verbose_name="Activity type"),
        ),
    ]
