# Generated by Django 2.2.6 on 2020-11-16 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Max: 250 symbols", max_length=250),
                ),
                (
                    "category",
                    models.CharField(help_text="Max: 250 symbols", max_length=250),
                ),
                (
                    "slug",
                    models.CharField(help_text="Max: 250 symbols", max_length=250),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Text (2000 chars max)",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                ("on_image", models.ImageField(upload_to="")),
                ("off_image", models.ImageField(upload_to="")),
                ("animation", models.FileField(upload_to="")),
                (
                    "how_to",
                    models.TextField(
                        help_text="Text (2000 chars max)",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                (
                    "share",
                    models.TextField(
                        help_text="Text (2000 chars max)",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
            },
        ),
        migrations.AddConstraint(
            model_name="reward",
            constraint=models.UniqueConstraint(fields=("slug",), name="unique slug"),
        ),
    ]
