# Generated by Django 2.2.6 on 2020-12-04 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="position",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="reward",
            name="share",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Text (2000 chars max)",
                null=True,
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
    ]
