# Generated by Django 4.2.18 on 2025-07-24 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0002_auto_20201204_0530"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reward",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
