"""
Django settings for Active10 project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from os import getenv, path
from pathlib import Path

# Build paths inside the project like this: path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv("DJANGO_SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
APP_ENV = getenv("APP_ENV", "development")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = APP_ENV == "development"

ALLOWED_HOSTS = ["*"]

USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    "baton",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "baton.autodiscover",
    "rest_framework",
    "drf_yasg",
    "colorful",
    "health_check",
    "health_check.db",
    "health_check.contrib.migrations",
    "storages",
    "reversion",
    "ckeditor",
    "admin_ordering",
    "adminsortable2",
    "subject_imagefield",
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    "two_factor",
    "django_password_validators",
    "django_password_validators.password_history",
    "zxcvbn_password",
    "applications.about_one_you.apps.AboutOneYouConfig",
    "applications.discover.apps.DiscoverConfig",
    "applications.faq.apps.FaqConfig",
    "applications.my_walks.apps.MyWalksConfig",
    "applications.goals.apps.GoalsConfig",
    "applications.tips.apps.TipsConfig",
    "applications.how_it_works.apps.HowItWorksConfig",
    "applications.onboarding.apps.OnboardingConfig",
    "applications.versions.apps.VersionsConfig",
    "applications.notifications.apps.NotificationsConfig",
    "applications.global_rules.apps.GlobalRulesConfig",
    "applications.rewards.apps.RewardsConfig",
    "applications.legals.apps.LegalsConfig",
    "applications.articles.apps.ArticlesConfig",
    "applications.views.apps.ViewsConfig",
    "applications.walking_plans.apps.WalkingPlansConfig",
    "csp",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "active10.middleware.Enforce2FA",
    "active10.middleware.AdminSanitizationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "csp.middleware.CSPMiddleware",
    "active10.middleware.SecurityHeadersMiddleware",
    "active10.middleware.RemoveServerHeaderMiddleware",
    "active10.middleware.HostValidationMiddleware",
]

ROOT_URLCONF = "active10.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

HEALTH_CHECK = {
    "DISK_USAGE_MAX": 90,  # percent
    "MEMORY_MIN": 100,  # in MB
}

WSGI_APPLICATION = "active10.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": f"django.db.backends.{getenv('DATABASE_ENGINE', 'postgresql')}",
        "NAME": getenv("DB_NAME", "active10_development"),
        "USER": getenv("DB_USER", "postgres"),
        "PASSWORD": getenv("DB_PASSWORD", ""),
        "HOST": getenv("DB_HOST", "localhost"),
        "PORT": getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "django_password_validators.password_history.password_validation.UniquePasswordsValidator",  # noqa: E501
        "OPTIONS": {
            "last_passwords": 3  # Only the last 3 passwords entered by the user
        },
    },
    {
        "NAME": "django_password_validators.password_character_requirements.password_validation.PasswordCharacterValidator",  # noqa: E501
        "OPTIONS": {
            "min_length_digit": 1,
            "min_length_alpha": 2,
            "min_length_special": 1,
            "min_length_lower": 1,
            "min_length_upper": 1,
            "special_characters": "~!@#$%^&*()_+{}\":;'[]",
        },
    },
    {
        "NAME": "zxcvbn_password.ZXCVBNValidator",
        "OPTIONS": {
            "min_score": 3,
            "user_attributes": ("username", "email", "first_name", "last_name"),
        },
    },
]

CKEDITOR_CONFIGS = {
    "default": {
        "toolbar_Basic": [
            [
                "Source",
                "-",
                "Bold",
                "Italic",
                "Strike",
                "-",
                "RemoveFormat",
                "-",
                "NumberedList",
                "BulletedList",
                "-",
                "Styles",
                "Format",
                "-",
                "Link",
                "Unlink",
            ],
        ],
        "toolbar": "Custom",
        "toolbar_Custom": [
            ["NumberedList", "BulletedList"],
            ["Link", "Unlink"],
            ["Bold", "Italic", "Underline"],
            ["Format", "Styles"],
        ],
        "height": 300,
        "width": 900,
    },
}

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

BATON = {
    "CHANGELIST_FILTERS_ALWAYS_OPEN": True,
    "SITE_HEADER": "Active10 CMS",
    "SITE_TITLE": "Active10 CMS",
    "INDEX_TITLE": "Site administration",
    "SUPPORT_HREF": "https://flipsidegroup.com/contact.html",
    "COPYRIGHT": 'copyright © 2024 <a href="https://flipsidegroup.com/">Flipside</a>',
    "POWERED_BY": '<a href="https://flipsidegroup.com/">Flipside</a>',
    "MENU": (
        {"type": "title", "label": "management", "apps": ("auth",)},
        {
            "type": "app",
            "name": "auth",
            "label": "Authentication",
            "icon": "fa fa-user-secret",
            "models": (
                {"name": "user", "label": "Users"},
                {"name": "group", "label": "Groups"},
            ),
        },
        {
            "type": "free",
            "label": "Security",
            "icon": "fa fa-lock",
            "children": [
                {
                    "type": "free",
                    "label": "Setup 2FA",
                    "url": "/account/two_factor/setup",
                },
                {
                    "type": "free",
                    "label": "My backup tokens",
                    "url": "/account/two_factor/backup/tokens/",
                },
                {"type": "free", "label": "Profile", "url": "/account/two_factor/"},
            ],
        },
        {"type": "title", "label": "content", "apps": ("about_one_you",)},
        {
            "type": "app",
            "name": "about_one_you",
            "label": "About Better Health",
            "models": (
                {"name": "aboutoneyou", "label": "About Better Health"},
                {"name": "application", "label": "Apps"},
            ),
        },
        {
            "type": "app",
            "name": "articles",
            "label": "Articles",
            "models": (
                {"name": "articlecategory", "label": "Article Categories"},
                {"name": "article", "label": "Articles"},
                {"name": "image", "label": "Images"},
            ),
        },
        {
            "type": "app",
            "name": "discover",
            "label": "Discover",
            "models": (
                {"name": "cta", "label": "CTA"},
                {"name": "carousel", "label": "Carousels"},
                {"name": "discover", "label": "Discover"},
                {"name": "splashscreen", "label": "Splash Screen"},
            ),
        },
        {
            "type": "app",
            "name": "my_walks",
            "label": "Dynamic Texts",
            "models": (
                {"name": "mywalk", "label": "My walks dynamic text"},
                {"name": "todaywalk", "label": "Today's walks dynamic text"},
            ),
        },
        {
            "type": "app",
            "name": "faq",
            "label": "FAQ",
            "models": ({"name": "faq", "label": "FAQs"},),
        },
        {
            "type": "app",
            "name": "global_rules",
            "label": "Global Rules",
            "models": (
                {"name": "accessibility", "label": "Accessibility Statement"},
                {"name": "link", "label": "Links"},
                {"name": "missingdata", "label": "Missing Data"},
                {"name": "appversion", "label": "Mobile App Versions"},
                {"name": "app", "label": "Operating Systems"},
                {"name": "termsconditions", "label": "Terms & Conditions"},
            ),
        },
        {
            "type": "app",
            "name": "goals",
            "label": "Goals",
            "models": ({"name": "goal", "label": "User Goals"},),
        },
        {
            "type": "app",
            "name": "how_it_works",
            "label": "How It Works",
            "models": ({"name": "howitworks", "label": "How It Works"},),
        },
        {
            "type": "app",
            "name": "legals",
            "label": "Legals",
            "models": ({"name": "legal", "label": "Legals"},),
        },
        {
            "type": "app",
            "name": "notifications",
            "label": "Notifications",
            "models": (
                {"name": "lapsed", "label": "Lapsed"},
                {"name": "onboarding", "label": "Onboarding"},
                {"name": "reminder", "label": "Reminders"},
                {"name": "userinfo", "label": "User Info's"},
                {"name": "localnotification", "label": "Local Notifications"},
            ),
        },
        {
            "type": "app",
            "name": "onboarding",
            "label": "On boarding",
            "models": ({"name": "readytogetstarted", "label": "Ready to get started"},),
        },
        {
            "type": "app",
            "name": "rewards",
            "label": "Rewards",
            "models": ({"name": "reward", "label": "Rewards"},),
        },
        {
            "type": "app",
            "name": "tips",
            "label": "Tips",
            "models": ({"name": "maintip", "label": "Tips"},),
        },
        {
            "type": "app",
            "name": "versions",
            "label": "Versions",
            "models": ({"name": "versionsset", "label": "Versions"},),
        },
        {
            "type": "app",
            "name": "views",
            "label": "Views",
            "models": ({"name": "view", "label": "Views"},),
        },
        {
            "type": "app",
            "name": "walking_plans",
            "label": "Walking Plans",
            "models": ({"name": "walkingplan", "label": "Walking Plans"},),
        },
    ),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

if getenv("AWS_STORAGE_BUCKET_NAME", None) is not None:
    REDIRECT_STATIC_TO_CDN = True
    AWS_ACCESS_KEY_ID = getenv("AWS_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = getenv("AWS_SECRET_ACCESS_KEY", "")
    AWS_STORAGE_BUCKET_NAME = getenv("AWS_STORAGE_BUCKET_NAME", "")

    # Consider making a variable as well
    AWS_LOCATION = "eu-west-2"

    AWS_S3_CUSTOM_DOMAIN = getenv("CDN_DOMAIN", f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com")

    # s3 static settings
    STATIC_LOCATION = ""
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
    STATICFILES_STORAGE = "storages.backends.s3boto3.S3StaticStorage"

    # s3 public media settings
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
    DEFAULT_FILE_STORAGE = "active10.s3utils.MediaRootS3BotoStorage"

    # For CKEditor
    AWS_QUERYSTRING_AUTH = False
else:
    REDIRECT_STATIC_TO_CDN = False
    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/3.1/howto/static-files/
    STATIC_URL = "/api/v1/active10/static/"
    MEDIA_URL = "/api/v1/active10/media/"
    MEDIA_ROOT = path.join(BASE_DIR, "media")
    STATIC_ROOT = path.join(BASE_DIR, "static")

SWAGGER_SETTINGS = {"USE_SESSION_AUTH": True}

LOGIN_URL = "two_factor:login"

# this one is optional
LOGIN_REDIRECT_URL = "two_factor:profile"
TWO_FACTOR_PATCH_ADMIN = True
# LOGIN_REDIRECT_URL = '/'

CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "https://active10.stg.phedigital.co.uk",
    "https://active10.prod.phedigital.co.uk/",
]

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Security Settings
# SECURE_SSL_REDIRECT = True  # Redirect all non-HTTPS requests to HTTPS
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

CSRF_COOKIE_SECURE = True  # Ensures the CSRF cookie is only sent over HTTPS
CSRF_COOKIE_AGE = 86400  # 1 day
SESSION_COOKIE_SECURE = True  # Ensures the session cookie is only sent over HTTPS
SESSION_COOKIE_AGE = 86400  # 1 day

CSP_DEFAULT_SRC = ("'self'", "*.s3.amazonaws.com", AWS_S3_CUSTOM_DOMAIN, "https://www.gravatar.com")
CSP_STYLE_SRC = (
    "'self'",
    "*.s3.amazonaws.com",
    AWS_S3_CUSTOM_DOMAIN,
    "https://www.gravatar.com",
    "'unsafe-inline'",
)
CSP_SCRIPT_SRC = (
    "'self'",
    "*.s3.amazonaws.com",
    AWS_S3_CUSTOM_DOMAIN,
    "https://www.gravatar.com",
    "'unsafe-inline'",
)
CSP_IMG_SRC = ("'self'", "*.s3.amazonaws.com", AWS_S3_CUSTOM_DOMAIN, "https://www.gravatar.com")
CSP_FONT_SRC = ("'self'", "*.s3.amazonaws.com", AWS_S3_CUSTOM_DOMAIN, "https://www.gravatar.com")
