# Generated by Django 3.1.2 on 2021-10-11 14:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Legal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("terms_and_conditions", "Terms and Conditions"),
                            ("accessibility", "Accessibility"),
                            ("privacy_policy", "Privacy Policy"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=128)),
                ("content", ckeditor.fields.RichTextField(blank=True, default="")),
                ("should_accept", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=0)),
                ("public", models.BooleanField(default=False)),
            ],
        ),
    ]
